### ISSUE TITLE
Server Client Version Mismatch

### ISSUE THREAD

**Issue by BeccaAsHeck** [bdew-minecraft/bdlib#53] opened 2021-05-25 20:51 UTC
Hey so I'm running this inside a pack with someone on a server, and I keep receiving a version mismatch error. I double checked the file versions several times, switched between 1.15.0.4 and 1.15.0.3, redownloaded the file several times to be absolutely sure. Is this simply related to early stages of porting over to 1.16.5? It seems to work for my bf but not for me.

The error in the log file is always the same one:
```[25May2021 22:36:10.375] [Netty Client IO #1/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [bdlib:multiblock] rejected their server side version number```

I appreciate your work though

Regards
Becca

**Comment by bdew** [comment] 2021-05-30 07:02
I can't reproduce this.

Make sure the mod is installed on both the client and the server, and that the version is the same.

If it still doesn't work post your debug.log from both server and client.

**Comment by CanBoy67** [comment] 2021-05-31 01:26
I had the exact same issue with this mod and only fixed it by flat out removing this mod and advanced generators from pack and server 
[Client debug.log](https://gist.github.com/CanBoy67/692b5a20f7f6380bd7b071ee8d58399f)

**Comment by bdew** [comment] 2021-05-31 05:24
@CanBoy67 from your log:

    Channel 'bdlib:multiblock' : Version test of 'ABSENT ?' from server : REJECTED

which means the mod is either not loaded on the server or something is broken on the other side (that's why i asked for both logs)

**Comment by BeccaAsHeck** [comment] 2021-06-02 16:36
[Client debug log](https://github.com/bdew-minecraft/bdlib/files/6586144/debug.log)
[Server debug log](https://github.com/bdew-minecraft/bdlib/files/6586146/debug.log)

These are both logs

![image](https://user-images.githubusercontent.com/84813510/120517956-506f8880-c3d1-11eb-8c3a-e8641c561ba1.png)
I just replaced bdlib both on client and server with the same downloaded file

Edit: Forgot to mention the error is persisting through the latest update

**Comment by bdew** [comment] 2021-06-03 06:14
I think i see what the problem is, something is causing Advanced Generators to touch the code for a channel in BdLib before it was properly initialized and it gets the wrong mod id...

Still can't reproduce it on my test server, but i'll change how that bit works to hopefully fix it.

**Comment by bdew** [comment] 2021-06-03 06:35
Please try with the following versions and let me know if it fixes the issue:

* BdLib - 1.17.0.8 https://www.curseforge.com/minecraft/mc-mods/bdlib/files/3335950
* Advanced Generators 0.10.1.10 - https://www.curseforge.com/minecraft/mc-mods/advanced-generators/files/3335951
* Compacter 1.4.1.5 - https://www.curseforge.com/minecraft/mc-mods/compacter/files/3335952 (if you use that mod, update it too)

**Comment by DaBultz** [comment] 2021-06-09 10:15
I had the exact same issue as the other people in this thread, after updating to the versiosn above it fixed the issue for me.

**Comment by bdew** [comment] 2021-06-10 14:11
Great i'm closing this then, if anyone still has problems with the fixed version feel free to reopen.

**Closed as completed by bdew** 2021-06-10 14:11 UTC
