### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by topher2010** [bdew-minecraft/bdlib#33] opened 2016-12-05 17:50 UTC
http://pastebin.com/mrj75sZN

Getting this crash when our server is on an auto-startup script.  everytime.

**Comment by bdew** [comment] 2016-12-05 20:08
That error makes 0% sense to me, the method shown in the stack trace is a 1 liner that shouldn't even be capable of throwing any exceptions. That's either coremod shenanigans or a something borked in the JVM.

What was the last thing you changed in your setup before it started?

**Comment by bdew** [comment] 2016-12-05 20:15
Actually looking into it some more it looks like the server watchdog is causing the shutdown...

What is max-tick-time set to in your properties file?

Also there should be a line like that in the log:

> A single server tick took ___ seconds (should be max ___ )

What does it say?

**Comment by topher2010** [comment] 2016-12-05 20:21
max-tick-time=60000

We don't see a line in our log that looks like what you described, fyi.

**Comment by bdew** [comment] 2016-12-05 20:33
Hm, then i still don't have any idea what might be going on here.

I did a bit of googling and the only instance of that error that i found was [this crash report](http://pastebin.com/8uyyTUhK) that looks like the same weird error but doesn't involve any of my mods. That log seems to be from [this issue](https://github.com/SleepyTrousers/EnderIO/issues/3524) but it doesn't really have anything helpful.

**Comment by topher2010** [comment] 2016-12-05 20:37
Is there anything we can do on our end to try to help figure this out?

**Comment by bdew** [comment] 2016-12-05 20:39
No idea at this moment, sorry. If i think of something i'll let you know.

**Comment by demethan** [comment] 2016-12-05 20:43
We are going to update our wrapper "MARK2" and  java just to make sure.

**Comment by topher2010** [comment] 2016-12-08 16:09
http://paste.ubuntu.com/23598970/

Updated to latest BDLib, getting this crash on server startup now.

*EDIT*: Also updated Forge to 2185

**Comment by demethan** [comment] 2016-12-12 14:25
@bdew , I could zip up the server and drop it here if you like. To try to reproduce the problem.

**Comment by topher2010** [comment] 2016-12-12 17:43
Another crash on server reboot.

http://pastebin.com/rvxjGFLS

**Comment by bdew** [comment] 2016-12-12 19:25
> @bdew , I could zip up the server and drop it here if you like. To try to reproduce the problem.

Sure, go ahead

**Comment by bdew** [comment] 2017-10-12 16:51
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:51 UTC
