### ISSUE TITLE
bdLib error

### ISSUE THREAD

**Issue by MihailDenisov** [bdew-minecraft/bdlib#6] opened 2014-09-29 17:34 UTC
I used the bdLib, as it was required by the modification. 
BUT. I ran into a problem - the game is broken. 
It is equally as broken with a bunch of mods, and without them (bdlib only). 

---- Minecraft Crash Report ----
// Don't do that.

Time: 29.09.14 21:22
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/Predef$any2stringadd$
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: scala/Predef$any2stringadd$
    at net.bdew.lib.network.NetChannel.addHandler(NetChannel.scala:73)
    at net.bdew.lib.network.NetChannel.init(NetChannel.scala:57)
    at net.bdew.lib.BdLib$.preInit(BdLib.scala:36)
    at net.bdew.lib.BdLib.preInit(BdLib.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: scala.Predef$any2stringadd$
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 41 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 116302960 bytes (110 MB) / 244113408 bytes (232 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.84.1217 Minecraft Forge 10.13.1.1217 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.84.1217} [Forge Mod Loader](forge-1.7.10-10.13.1.1217.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.1.1217} [Minecraft Forge](forge-1.7.10-10.13.1.1217.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.4.5.24} [BD Lib](bdlib-mc1710-1.4.5.24.jar) Unloaded->Constructed->Errored

**Comment by bdew** [comment] 2014-09-29 17:49
Forge 10.13.1.x is not supported and will probably need a separate build, looks like more shenanigans with Scala libraries versions.

Also in the future please put the crash report on pastebin or gist, having the whole thing here is a mess.

**Comment by bdew** [comment] 2014-09-29 18:02
Actually scratch what i said, i can't reproduce this with the given versions. 

Might be a broken installation or something.

Please provide a full log.

**Comment by MihailDenisov** [comment] 2014-09-29 18:17
Full log
http://pastebin.com/8XincSkS

**Comment by bdew** [comment] 2014-09-29 18:34
> C:\Users\Mariya\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-library\2.10.2\scala-library-2.10.2

Yeah your setup is broken. For forge 10.13.1 (and 0) this should be version 2.11.1

How are you launching the game? If it's the vanilla launcher - try deleting your forge profile and reinstalling.

**Comment by MihailDenisov** [comment] 2014-09-29 19:10
Yes, it is a regular license launcher.
Thanks, now I will try.

**Comment by MihailDenisov** [comment] 2014-09-29 19:26
Eureka!
This mod is not compatible with auto-installed LiteLoader!
Apparently, the LiteLoader corrupts libraries...

**Comment by bdew** [comment] 2014-09-29 19:36
There shouldn't be anything incompatible with LL by itself, if it's installer messes up Forge environment - then it's a bug in it's installer and will break every single mod written in scala. Anyway there is nothing i can do about this on my side so i'm closing this.

**Closed as completed** 2014-09-29 19:36 UTC
